/* Generated by scripts/github.mjs on 2026-10-09: do not edit by hand, run
   `npm run github` and commit the result. What the GitHub card and the
   chat's FACTS know about the public account; see the script for what is
   counted and why only project repos are listed. */

export type GithubRepo = {
  name: string;
  /** The project's title in projects.ts, or "This site". */
  title: string;
  /** The project's slug, or null for this site's own repo. */
  slug: string | null;
  url: string;
  language: string;
  /** ISO date of the last push, and the same for reading. */
  pushedAt: string;
  pushed: string;
};

export const GITHUB: {
  user: string;
  url: string;
  asOf: string;
  asOfPretty: string;
  memberSince: string;
  publicRepos: number;
  windowDays: number;
  pushes: number;
  reposPushed: number;
  repos: GithubRepo[];
} = {
  "user": "Toshkee",
  "url": "https://github.com/Toshkee",
  "asOf": "2026-10-09",
  "asOfPretty": "9 Oct 2026",
  "memberSince": "2024",
  "publicRepos": 56,
  "windowDays": 30,
  "pushes": 47,
  "reposPushed": 7,
  "repos": [
    {
      "name": "Pavle-Tosic",
      "title": "This site",
      "slug": null,
      "url": "https://github.com/Toshkee/Pavle-Tosic",
      "language": "TypeScript",
      "pushedAt": "2026-10-09",
      "pushed": "9 Oct 2026"
    },
    {
      "name": "CryptoFlow",
      "title": "CryptoFlow",
      "slug": "cryptoflow",
      "url": "https://github.com/Toshkee/CryptoFlow",
      "language": "TypeScript",
      "pushedAt": "2026-10-08",
      "pushed": "8 Oct 2026"
    },
    {
      "name": "Vaky.me",
      "title": "Vaky.me",
      "slug": "vaky",
      "url": "https://github.com/Toshkee/Vaky.me",
      "language": "TypeScript",
      "pushedAt": "2026-10-08",
      "pushed": "8 Oct 2026"
    },
    {
      "name": "MandarinaPetrovac",
      "title": "Mandarina, Petrovac",
      "slug": "mandarina-petrovac",
      "url": "https://github.com/Toshkee/MandarinaPetrovac",
      "language": "Astro",
      "pushedAt": "2026-09-16",
      "pushed": "16 Sept 2026"
    },
    {
      "name": "VillaVucje",
      "title": "Villa Vučje",
      "slug": "villa-vucje",
      "url": "https://github.com/Toshkee/VillaVucje",
      "language": "Astro",
      "pushedAt": "2026-09-16",
      "pushed": "16 Sept 2026"
    },
    {
      "name": "anime-watchlist",
      "title": "Arc: Anime Tracker",
      "slug": "arc-anime-tracker",
      "url": "https://github.com/Toshkee/anime-watchlist",
      "language": "TypeScript",
      "pushedAt": "2026-07-01",
      "pushed": "1 Jul 2026"
    },
    {
      "name": "Ronin-Duel",
      "title": "Ronin Duel",
      "slug": "ronin-duel",
      "url": "https://github.com/Toshkee/Ronin-Duel",
      "language": "TypeScript",
      "pushedAt": "2026-07-01",
      "pushed": "1 Jul 2026"
    },
    {
      "name": "Meet2Explore-Frontend",
      "title": "Meet2Explore",
      "slug": "meet2explore",
      "url": "https://github.com/Toshkee/Meet2Explore-Frontend",
      "language": "JavaScript",
      "pushedAt": "2025-11-26",
      "pushed": "26 Nov 2025"
    }
  ]
};
