/* Regenerates src/app/site/github.ts from the public GitHub API: the
   account in numbers (public repos, pushes lately) and the last push to
   each repo that is a project in projects.ts. Only those repos are listed,
   so every name on the GitHub card is one the chat's FACTS can speak
   about; the totals count everything public. Nothing is fetched at
   runtime (the CSP allows no such origin, and the model must only know
   what is written down), so run `npm run github` and commit the file:
   the card says the date it was counted.

   Unauthenticated: 60 requests an hour is plenty for three. */

import { readFile, writeFile } from "node:fs/promises";

const USER = "Toshkee";
// This site's own repo is not a project in projects.ts but belongs on
// the list: it is the one a visitor is looking at.
const SITE_REPO = { url: `https://github.com/${USER}/Pavle-Tosic`, title: "This site" };
const WINDOW_DAYS = 30;

const api = async (path) => {
  const res = await fetch(`https://api.github.com${path}`, {
    headers: { Accept: "application/vnd.github+json", "User-Agent": "pavletosic.com" },
  });
  if (!res.ok) throw new Error(`GitHub ${path} returned ${res.status}`);
  return res.json();
};

const [user, repos, events] = await Promise.all([
  api(`/users/${USER}`),
  api(`/users/${USER}/repos?per_page=100&sort=pushed`),
  api(`/users/${USER}/events/public?per_page=100`),
]);

// The project repos, read out of projects.ts the way check-site.mjs reads
// the slugs: plain node cannot import a .ts file.
const src = await readFile(new URL("../src/app/projects.ts", import.meta.url), "utf8");
const projects = [
  ...src.matchAll(/^\s{4}slug: "([^"]+)",\n\s{4}title: "([^"]+)",[\s\S]*?^\s{4}code: (?:null|"([^"]+)")/gm),
].map(([, slug, title, code]) => ({ slug, title, code: code ?? null }));
if (projects.length === 0) throw new Error("no projects found in projects.ts");

// The events feed covers at most 90 days or 300 events; the window is the
// shorter of 30 days and what the feed actually holds.
const now = Date.now();
const oldest = events.at(-1)?.created_at;
const windowDays = oldest
  ? Math.min(WINDOW_DAYS, Math.ceil((now - Date.parse(oldest)) / 86_400_000))
  : WINDOW_DAYS;
const since = now - windowDays * 86_400_000;
const pushes = events.filter((e) => e.type === "PushEvent" && Date.parse(e.created_at) >= since);
const reposPushed = new Set(pushes.map((e) => e.repo.name)).size;

const day = (iso) =>
  new Date(iso).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric", timeZone: "UTC" });

const listed = [SITE_REPO, ...projects.filter((p) => p.code).map((p) => ({ url: p.code, title: p.title, slug: p.slug }))]
  .map(({ url, title, slug }) => {
    const repo = repos.find((r) => r.html_url.toLowerCase() === url.toLowerCase());
    if (!repo) {
      console.warn(`  skip ${url}: not among ${USER}'s public repos`);
      return null;
    }
    return {
      name: repo.name,
      title,
      slug: slug ?? null,
      url: repo.html_url,
      language: repo.language ?? "",
      pushedAt: repo.pushed_at.slice(0, 10),
      pushed: day(repo.pushed_at),
    };
  })
  .filter(Boolean)
  .sort((a, b) => (a.pushedAt < b.pushedAt ? 1 : -1));

const asOf = new Date(now).toISOString().slice(0, 10);
const data = {
  user: USER,
  url: user.html_url,
  asOf,
  asOfPretty: day(asOf),
  memberSince: user.created_at.slice(0, 4),
  publicRepos: user.public_repos,
  windowDays,
  pushes: pushes.length,
  reposPushed,
  repos: listed,
};

const out = `/* Generated by scripts/github.mjs on ${asOf}: do not edit by hand, run
   \`npm run github\` and commit the result. What the GitHub card and the
   chat's FACTS know about the public account; see the script for what is
   counted and why only project repos are listed. */

export type GithubRepo = {
  name: string;
  /** The project's title in projects.ts, or "This site". */
  title: string;
  /** The project's slug, or null for this site's own repo. */
  slug: string | null;
  url: string;
  language: string;
  /** ISO date of the last push, and the same for reading. */
  pushedAt: string;
  pushed: string;
};

export const GITHUB: {
  user: string;
  url: string;
  asOf: string;
  asOfPretty: string;
  memberSince: string;
  publicRepos: number;
  windowDays: number;
  pushes: number;
  reposPushed: number;
  repos: GithubRepo[];
} = ${JSON.stringify(data, null, 2)};
`;

await writeFile(new URL("../src/app/site/github.ts", import.meta.url), out);
console.log(
  `github.ts: ${data.publicRepos} public repos, ${data.pushes} pushes to ${data.reposPushed} repos in ${windowDays} days, ${listed.length} project repos listed (as of ${asOf})`,
);
